### ISSUE TITLE
RuntimeError: Error compiling objects for extension

### ISSUE THREAD

**Issue by zijianh4** [happinesslz/EPNet#42]
Hi, 
Thanks for your great work! When I try to run `bash build_and_install.sh` to install packages, it shows `RuntimeError: Error compiling objects for extension`. My environment is python 3.7.4, torch 1.10.0, cuda 11.3. Could you please help me to figure out this error? Thanks!

**Comment by zijianh4** [comment]
It seems that it is because the PyTorch and Cuda version is too high. However, when I use PyTorch 1.2 and cuda 10, I meet this error: `RuntimeError: cuDNN error: CUDNN_STATUS_MAPPING_ERROR`. Do you know how to fix it? Thanks!

**Comment by faziii0** [comment]
try with python 3.8 cuda 11.3 and cuda dev 11.3

**Comment by tianl18** [comment]
ref: https://github.com/sshaoshuai/Pointnet2.PyTorch/pull/42/files
and https://github.com/sshaoshuai/PointRCNN/pull/184/files

it works for me. CUDA 11.1 PyTorch 1.8.1+cu111 in A800
